config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"

  get 'home', to: 'pages#home'
  root to: 'pages#home'
  get 'about', to: 'pages#about', as: 'about'
  get 'work', to: 'pages#work', as: 'work'
  get 'contact', to: 'pages#contact', as: 'contact'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
    def home
        render :home
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DevPortfolio</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/pages/about.html.erb
<h1>About Lea Verou</h1>

<body>
    <p>Lea Verou is a computer scientist who is from Lesbos, Greece. She got her Bachelor of Science degree from Athens University of Economics and Business. She then earned a Master of science degree from MIT. She is currently a member of W3C Technical Architecture Group and her job is to design web technologies.</p>

    <p><%= link_to "Back to Home", home_path %></p>
</body>

app/views/pages/contact.html.erb
<h1>Contact Info</h1>

<body>
    <ul>
        <li>Website: https://lea.verou.me/</li>
        <li>Email: lea@verou.me</li>
        <li>Twitter: @LeaVerou</li>
        <li>GitHub: LeaVerou</li>
    </ul>

    <p><%= link_to "Back to Home", home_path %></p>
</body>

app/views/pages/home.html.erb
<h1>Lea Verou</h1>

<body>
    <p>Hello, this page serves to be a portfolio for Lea Verou. She is a web developer who specializes in designing web technologies, with the goal of making web programming easier.</p>

    <h3>Links</h3>
    <ul>
        <li><%= link_to "About", about_path %></li>
        <li><%= link_to "Works", work_path %></li>
        <li><%= link_to "Contact Info", contact_path %></li>
    </ul>
</body>

app/views/pages/work.html.erb
<h1>Works</h1>

<body>
    <ul>
        <li>Mavo: This is a programming language Verou developed that extends the syntax of HTML for the purpose of making it easier to develop web applications.</li>
        <li>PrismJS: This is a syntax highlighter she made that is used for highlighting in HTML.</li>
    </ul>

    <p><%= link_to "Back to Home", home_path %></p>
</body>